### ISSUE TITLE
Collaborative Photo Sharing App not anymore

### ISSUE THREAD

**Issue by bsubramaniam** [wgqtdhvz1/test#17]
## Phase 1: Setting up Portfolio
-   [X] Build signup & login flow
-   [X] Allow new user to signup via email
-   [X] Allow existing users to login with email & password
-   [ ] Create empty portfolio page on first login
-   [ ] Allow users to upload pictures to portfolio
-   [ ] Users can add a description to each picture
-   [ ] Users can categorize pictures with hashtags and location
## Phase 2: Sharing & collaboration
-   [ ] Allow users to invite others to their portfolio page
-   [ ] Existing users should get a direct link to shared portfolio
-   [ ] Invite the new user to create account & join portfolio
-   [ ] All shared users can add and update pictures to the portfolio
-   [ ] Only the creator or portfolio owner can delete pictures
-   [ ] Allow users to publicly share portflio
-   Should generate a sharable public link to the portfolio page
-   Non-logged in users and users not shared in portfolio will have Guest Access
## Phase 3: Comments & Notifications
-   [ ] Users can comment on any picture on the portfolio
-   [ ] All shared users will recieve email notifications:
-   [ ] When a new picture is added
-   [ ] When a comment is added
-   [ ] Users can message others shared in the portfolio
## Phase 4: Realtime sync & Push notifications
-   [ ] Reflect updates in real-time
-   [ ] Push notifications via webhooks
-   [ ] Generate activity stream
